### ISSUE TITLE
Allow removal/reautocreation of filters previously created by squidguardmgr

### ISSUE THREAD

**Issue by e-gaulue** [darold/squidguardmgr#39]
This is an improvement request.

Filters created by squidguardmgr auto configuration features could go in a zone inside:
```
# DON'T REMOVE THIS LINE NEEDED BY SQUIDGUARDMGR : FILTERS BEGIN
dest adv {
        domainlist      adv/domains
        urllist adv/urls
}
dest aggressive {
        domainlist      aggressive/domains
        urllist aggressive/urls
}
...
dest webtv {
        domainlist      webtv/domains
        urllist webtv/urls
}
# DON'T REMOVE THIS LINE NEEDED BY SQUIDGUARDMGR : FILTERS END
```

This would allow users to remove them or reautocreate them with no arm to the rest of the file (except double filters name).

Regards,

**Comment by darold** [comment]
This won't be implemented, SquidGuardMgr need to takes full control of your configuration file, but you can always edit it by hand. SquidGuardMgr will take care of these manual changes.
