### ISSUE TITLE
cgi-pm error

### ISSUE THREAD

**Issue by malacmalac** [darold/squidguardmgr#42]
Hi,

When i open or manage lists, there is no content, and log shows:

CGI::param called in list context from package main line 114, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/share/perl5/CGI.pm line 436.

ii  libcgi-pm-perl                                4.09-1                      all                         module for Common Gateway Interface applications

debian jessie

Can you explain this problem?
Thanx
Laszlo

**Comment by darold** [comment]
Hi,

Last commit d2336b2 fixes call to CGI::param() in list context by using multi_param() instead. With new versions of CGI.pm this was producing error explained in chapter "Fetching the value or values of a single named parameter" of the CGI.pm documentation.
